name: Deploy Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Replace placeholders with secrets
      #   run: |
      #     sed -i 's/DEPLOYMENT_ID_PLACEHOLDER/${{ secrets.DEPLOYMENT_ID }}/g' index.html
      #     sed -i 's/DEPLOYMENT_SHEET_PLACEHOLDER/${{ secrets.DEPLOYMENT_SHEET }}/g' index.html
      #     sed -i 's/DEPLOYMENT_ID_PLACEHOLDER/${{ secrets.DEPLOYMENT_ID }}/g' edit.html
      #     sed -i 's/DEPLOYMENT_SHEET_PLACEHOLDER/${{ secrets.DEPLOYMENT_SHEET }}/g' edit.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
